
[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
upload_protocol = teensy-cli
lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    bluerobotics/BlueRobotics MS5837 Library @ ^1.1.1
    adafruit/Adafruit HMC5883 Unified @ ^1.2.3